### ISSUE TITLE
ValueError: need at least one array to stack

### ISSUE THREAD

**Issue by pavlosidelov** [ajkdrag/ocrtoolkit#2]
I use the code from example:
from ocrtoolkit.models import UL_YOLOV8
from ocrtoolkit.datasets import FileDS
from ocrtoolkit.core import detect

ds = FileDS("some_images_dir")
mini_ds = ds.sample()
model = UL_YOLOV8()

l_results = detect(model, mini_ds, stream=False)

All libs is installed.
Got the next error:

/OCR/ocrtoolkit$ python3 detect.py
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1068042/1068042 [00:05<00:00, 211473.43it/s]
2024-03-29 14:03:02.049 | INFO     | ocrtoolkit.utilities.io_utils:get_files:57 - Found 0 files.
2024-03-29 14:03:03.391 | INFO     | ocrtoolkit.wrappers.model:__init__:22 - Loaded model from yolov8n.pt, to cpu
2024-03-29 14:03:03.391 | INFO     | ocrtoolkit.core.detector:detect:30 - Stream mode: False
2024-03-29 14:03:03.391 | INFO     | ocrtoolkit.core.detector:detect:31 - Batched mode: True
2024-03-29 14:03:03.391 | INFO     | ocrtoolkit.core.detector:detect:32 - Running predict on 0 samples

Traceback (most recent call last):
  File "/OCR/ocrtoolkit/detect.py", line 9, in <module>
    l_results = detect(model, mini_ds, stream=False)
  File "/OCR/ocrtoolkit/lib/python3.10/site-packages/ocrtoolkit/core/detector.py", line 36, in detect
    return list(_detect(model, ds, **kwargs))
  File "/OCR/ocrtoolkit/lib/python3.10/site-packages/ocrtoolkit/core/detector.py", line 18, in _detect
    l_det_results = model.predict(l_inputs, **kwargs)
  File "/OCR/ocrtoolkit/lib/python3.10/site-packages/ocrtoolkit/wrappers/model.py", line 40, in predict
    return super().predict(images, **kwargs)
  File "/OCR/ocrtoolkit/lib/python3.10/site-packages/ocrtoolkit/wrappers/model.py", line 35, in predict
    return self._predict(images, **filtered_kwargs)
  File "/OCR/ocrtoolkit/lib/python3.10/site-packages/ocrtoolkit/integrations/ultralytics.py", line 14, in _predict
    l_preds = self.model.predict(images, **kwargs)
  File "/OCR/ocrtoolkit/lib/python3.10/site-packages/ultralytics/engine/model.py", line 451, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/OCR/ocrtoolkit/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/OCR/ocrtoolkit/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/OCR/ocrtoolkit/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 244, in stream_inference
    im = self.preprocess(im0s)
  File "/OCR/ocrtoolkit/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 124, in preprocess
    im = np.stack(self.pre_transform(im))
  File "/OCR/ocrtoolkit/lib/python3.10/site-packages/numpy/core/shape_base.py", line 445, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

**Comment by ajkdrag** [comment]
```python
ds = FileDS("some_images_dir")
```
Please replace "some_images_dir" with path to your own images folder.
As you can see from the error, it says:
```
024-03-29 14:03:02.049 | INFO | ocrtoolkit.utilities.io_utils:get_files:57 - Found 0 files.
```
Maybe folder name is not correct?

**Comment by pavlosidelov** [comment]
Dear @ajkdrag thank you for support.
I found the root cause. Folder was correct - the format of pictures was not standard, that's why script founds 0.
Now all works fine.
Case closed.

**Comment by ajkdrag** [comment]
Awesome! I `get_files` reads '.png', '.jpg', '.tif' and '.jpeg' formats as of now. 
Marking this as resolved.
